sonar.projectKey=ops4life_sre-framework
sonar.projectName=sre-framework
sonar.organization=ops4life

sonar.sources=app,frontend/src
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/dist/**,**/coverage/**

sonar.python.version=3.12
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
